###############################################################################
#
# GPS-tracker Project
#
# File:
#   configs/traefik/dynamic/compress.yml
#
###############################################################################

http:

  middlewares:

    compress:

      compress: {}