###############################################################################
#
# GPS-tracker Project
#
# File:
#   compose.yml
#
# Description:
#   Main Docker Compose entry point.
#
# Repository:
#   https://github.com/gregorku/GPS-tracker
#
# Requirements:
#   Docker Compose v2.20+
#
###############################################################################

name: grafana

include:

  ###########################################################################
  # Docker Networks
  ###########################################################################

  - compose/00-networks.yml

  ###########################################################################
  # Reverse Proxy
  ###########################################################################

  - compose/10-traefik.yml

  ###########################################################################
  # Security
  ###########################################################################

  - compose/20-crowdsec.yml

  ###########################################################################
  # Monitoring
  ###########################################################################

  - compose/30-metabase.yml

  ###########################################################################
  # Maintenance
  ###########################################################################

  - compose/40-watchtower.yml

  ###########################################################################
  # GPS Tracker
  ###########################################################################

  - compose/50-gps-tracker.yml

  ###########################################################################
  # Local Overrides
  ###########################################################################

  - compose/99-local.yml